import Link from "next/link";
import { Pencil } from "lucide-react";
import { notFound } from "next/navigation";
import { SupplierPaymentForm } from "@/components/suppliers/supplier-payment-form";
import { buttonVariants } from "@/components/ui/button";
import { requireWorkspace } from "@/lib/server/auth";
import { getSupplier } from "@/lib/server/suppliers";
import { formatDate, formatPKR } from "@/lib/utils";
export default async function SupplierPage({ params }: { params: Promise<{ id: string }> }) { const { workspaceId, role } = await requireWorkspace(); const supplier = await getSupplier(workspaceId, (await params).id); if (!supplier) notFound(); const canManage = role !== "STAFF"; return <div className="space-y-6"><header className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-neutral-500">Supplier khata</p><h1 className="text-2xl font-bold">{supplier.companyName ?? supplier.name}</h1><p className="mt-1 text-lg">Payable: <strong>{formatPKR(supplier.currentBalance)}</strong></p></div>{canManage && <Link href={`/suppliers/${supplier.id}/edit`} className={buttonVariants({ variant: "outline" })}><Pencil className="h-4 w-4" />Edit</Link>}</header>{canManage && <SupplierPaymentForm supplierId={supplier.id} />}<section className="border"><h2 className="border-b p-4 font-semibold">Ledger</h2><div className="divide-y">{supplier.ledgerEntries.map((entry) => <div key={entry.id} className="grid grid-cols-[1fr_auto] gap-4 p-4 text-sm"><div><p className="font-medium">{entry.description}</p><p className="text-neutral-500">{formatDate(entry.date.toISOString())}</p></div><p className="tabular-nums">{entry.credit ? `+${formatPKR(entry.credit)}` : `-${formatPKR(entry.debit)}`}</p></div>)}{!supplier.ledgerEntries.length && <p className="p-8 text-center text-neutral-500">No ledger entries.</p>}</div></section></div>; }
