import Link from "next/link";

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-[#f8faf9] px-5 py-12 text-slate-900 sm:px-6">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="text-sm font-semibold text-emerald-700">Back to MunshiOS</Link>
        <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-10">
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">Privacy</p>
          <h1 className="mt-3 text-4xl font-semibold tracking-tight">Privacy Policy</h1>
          <p className="mt-3 text-sm text-slate-500">Last updated September 19, 2026</p>
          <div className="mt-8 space-y-7 text-sm leading-7 text-slate-700">
            <section><h2 className="text-lg font-semibold text-slate-950">Scope</h2><p className="mt-2">MunshiOS is a business software service intended for authorized business users. It is not designed as a consumer service for children, and users should not create accounts for children or enter child data unless it is genuinely required for a lawful business purpose.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">What we collect</h2><p className="mt-2">MunshiOS may process account details, business identity and contact information, workspace records, customer and supplier records, tax identifiers, invoice and payment data, inventory records, device and diagnostic information, security events, and information users choose to enter into the service.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">How we use information</h2><p className="mt-2">We use information to provide and secure the service, operate accounting and inventory features, support users, maintain auditability, prevent abuse, improve reliability, and meet tax, legal, security, contractual, or compliance obligations.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">FBR Digital Invoicing</h2><p className="mt-2">When an authorized workspace enables FBR Digital Invoicing, MunshiOS may prepare and transmit required invoice, seller, buyer, tax and product information to FBR and to the licensed integrator or PRAL route configured for that workspace. Production transmission is intended to occur only after the required integration route has been configured and authorized. MunshiOS does not claim to be an FBR-licensed integrator unless a valid license is separately obtained and disclosed.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Data minimization</h2><p className="mt-2">We aim to collect and transmit only information reasonably needed for the feature being used. FBR submission records keep structured payload and response history for integrity, reconciliation, troubleshooting and audit purposes; authentication secrets and FBR access tokens must not be stored in ordinary invoice records or exposed to workspace users who do not need them.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Workspace separation and access</h2><p className="mt-2">Business records are scoped to a workspace and access is controlled through authenticated users, roles and permissions. Workspace owners and administrators are responsible for granting access only to authorized people and for removing access when it is no longer required.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Service providers and data transfers</h2><p className="mt-2">MunshiOS may use hosting, authentication, database, infrastructure, communications, payment and support providers. These providers may process data in locations outside Pakistan. We limit provider access to what is reasonably needed to operate the service and expect appropriate contractual and technical safeguards for the processing they perform.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Analytics and session recording</h2><p className="mt-2">MunshiOS does not currently use session-replay tools to record keystrokes or authenticated business screens. If that changes, the applicable notice, consent or other legal requirements and masking controls should be implemented before such recording is enabled.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">No sale of business data</h2><p className="mt-2">MunshiOS does not sell customer workspace records, invoice data, tax identifiers or other business records to advertisers or data brokers.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Retention and deletion</h2><p className="mt-2">We retain information while an account or workspace is active and for periods reasonably required for security, accounting integrity, tax records, statutory obligations, dispute handling, backups and audit history. Financial, tax and FBR transmission records may need to remain in an immutable or non-destructive history instead of being permanently deleted on demand.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Your choices</h2><p className="mt-2">Authorized users can update many business details from the product and may request account or data-related assistance through the support channels published by MunshiOS. A request to remove data may be limited where retention is required for accounting integrity, tax compliance, fraud prevention, security or another lawful obligation.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Security</h2><p className="mt-2">We use authentication, access controls, workspace scoping, audit trails and other safeguards designed to reduce unauthorized access, alteration or disclosure. No online service can guarantee absolute security, so users should also protect credentials, devices and administrator access.</p></section>
            <section><h2 className="text-lg font-semibold text-slate-950">Changes</h2><p className="mt-2">We may update this policy as MunshiOS, applicable law or connected compliance services evolve. Material changes will be reflected on this page with an updated revision date.</p></section>
          </div>
        </div>
      </div>
    </main>
  );
}
