import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BarChart3, Check, ChevronRight, CircleDollarSign, Factory, LayoutDashboard, PackageCheck, ReceiptText, ShieldCheck, ShoppingCart, Store, UtensilsCrossed, Warehouse } from "lucide-react";
import { MarketingHeader, MarketingFooter, SectionTitle, CTA } from "@/components/marketing/site";

function ProductFlowPreview() {
  const steps = [["PO-1048","Purchase order","Approved"],["GRN-0821","Goods receipt","Stock received"],["WH-MAIN","Inventory","+120 units"],["SUP-204","Supplier ledger","Updated"]] as const;
  return <div className="relative mx-auto w-full max-w-[760px] lg:translate-x-3">
    <div className="absolute -inset-10 -z-10 rounded-[48px] bg-[radial-gradient(circle_at_50%_42%,rgba(16,185,129,.20),transparent_66%)] blur-2xl"/>
    <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_36px_110px_-38px_rgba(15,23,42,.4)]">
      <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div className="flex gap-2">{[0,1,2].map(i=><span key={i} className="size-2.5 rounded-full bg-slate-200"/>)}</div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[0.12em] text-amber-700">Product interface preview · sample data</span></div>
      <div className="flex min-h-[440px]">
        <aside className="hidden w-44 shrink-0 bg-[#071821] p-4 text-white sm:block"><div className="flex items-center gap-2 border-b border-white/10 pb-4"><Image src="/brand/munshios-mark.svg" alt="" width={32} height={32}/><span className="text-sm font-semibold">MunshiOS</span></div><div className="mt-5 space-y-1.5 text-xs text-slate-400">{[[LayoutDashboard,"Dashboard"],[ReceiptText,"Sales"],[ShoppingCart,"Purchases"],[Warehouse,"Inventory"],[CircleDollarSign,"Accounting"],[PackageCheck,"GRN"],[BarChart3,"Reports"]].map(([Icon,label],index)=>{const NavIcon=Icon as typeof LayoutDashboard;return <div key={label as string} className={`flex items-center gap-2 rounded-lg px-2.5 py-2 ${index===2?"bg-emerald-500/15 text-emerald-300":""}`}><NavIcon className="size-3.5"/><span>{label as string}</span></div>})}</div></aside>
        <div className="min-w-0 flex-1 bg-[#f7faf9] p-4 sm:p-5"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-emerald-700">Connected purchase workflow</p><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-lg font-semibold text-slate-950">Purchase order to ledger</h3><p className="mt-1 text-xs text-slate-500">One workflow, four records kept in sync.</p></div><span className="rounded-xl bg-emerald-600 px-3 py-2 text-[10px] font-bold text-white">Live workflow pattern</span></div>
        <div className="mt-5 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] text-slate-500">Supplier</p><p className="mt-1 text-sm font-semibold">Sample Engineering Supplier</p></div><div className="text-right"><p className="text-[10px] text-slate-500">PO total</p><p className="mt-1 text-sm font-semibold">Rs. 286,400</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{[["Front hub blank","120 pcs"],["Bearing set","120 sets"],["Oil seal","120 pcs"]].map(([item,qty])=><div key={item} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-medium text-slate-800">{item}</p><p className="mt-1 text-[10px] text-slate-500">{qty}</p></div>)}</div></div>
        <div className="mt-3 grid gap-2 sm:grid-cols-4">{steps.map(([code,label,status],index)=><div key={code} className={`relative rounded-2xl border p-3 ${index===3?"border-emerald-200 bg-emerald-50":"border-slate-200 bg-white"}`}><p className="text-[9px] font-bold text-emerald-700">0{index+1}</p><p className="mt-3 text-[10px] font-semibold text-slate-900">{label}</p><p className="mt-1 text-[9px] text-slate-500">{code}</p><p className="mt-3 text-[9px] font-semibold text-emerald-700">{status}</p>{index<3&&<ChevronRight className="absolute -right-3 top-1/2 z-10 hidden size-4 -translate-y-1/2 text-emerald-500 sm:block"/>}</div>)}</div>
        <div className="mt-3 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-900"><Check className="size-4"/>Receiving updates stock and the supplier balance from the same workflow.</div></div></div>
      </div>
    </div>
  </div>
}

function MiniVisual({type}:{type:"wholesale"|"restaurant"|"manufacturing"|"retail"}) {
  if(type==="restaurant") return <div className="grid h-36 grid-cols-3 gap-2 rounded-2xl bg-[#071821] p-3">{[["NEW","5"],["PREP","7"],["READY","4"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/10 bg-white/5 p-2"><p className="text-[8px] font-bold text-slate-400">{a}</p><p className="mt-2 text-lg font-bold text-white">{b}</p><div className="mt-3 space-y-1">{[0,1,2].map(i=><div key={i} className="h-1.5 rounded bg-white/10"/>)}</div></div>)}</div>;
  if(type==="manufacturing") return <div className="h-36 rounded-2xl border border-slate-200 bg-[#f7faf9] p-4"><div className="flex items-end gap-2">{[38,72,54,88,64].map((h,i)=><div key={i} className="flex-1 rounded-t bg-emerald-500/80" style={{height:h}}/> )}</div><div className="mt-3 flex justify-between text-[8px] font-bold text-slate-400"><span>RAW</span><span>PRODUCTION</span><span>FG</span></div></div>;
  if(type==="retail") return <div className="h-36 rounded-2xl border border-slate-200 bg-[#f7faf9] p-3"><div className="grid grid-cols-3 gap-2">{[["Sales","126k"],["Low","9"],["Khata","214k"]].map(([a,b])=><div key={a} className="rounded-xl bg-white p-2"><p className="text-[8px] text-slate-400">{a}</p><p className="mt-1 text-sm font-bold">{b}</p></div>)}</div><div className="mt-2 space-y-1.5">{[0,1,2].map(i=><div key={i} className="flex items-center justify-between rounded-lg bg-white px-2 py-1.5"><span className="h-1.5 w-16 rounded bg-slate-200"/><span className="h-1.5 w-8 rounded bg-emerald-400"/></div>)}</div></div>;
  return <div className="h-36 rounded-2xl border border-slate-200 bg-[#f7faf9] p-3"><div className="grid grid-cols-3 gap-2">{[["Recv.","842k"],["Stock","2.1m"],["Due","14"]].map(([a,b])=><div key={a} className="rounded-xl bg-white p-2"><p className="text-[8px] text-slate-400">{a}</p><p className="mt-1 text-sm font-bold">{b}</p></div>)}</div><div className="mt-2 rounded-xl bg-white p-2">{["INV-1042","GRN-0821","RCPT-518"].map(x=><div key={x} className="flex justify-between border-b border-slate-100 py-1.5 last:border-0"><span className="text-[8px] font-bold text-emerald-700">{x}</span><span className="h-1.5 w-14 rounded bg-slate-200"/></div>)}</div></div>;
}

export default function Home(){return <main className="min-h-screen overflow-x-hidden bg-[#fbfcfa] text-[#0b1720]"><MarketingHeader/>
<section className="relative overflow-hidden border-b border-slate-200 bg-white"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_22%,rgba(16,185,129,.15),transparent_28%)]"/><div className="relative mx-auto grid max-w-[1400px] gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[.82fr_1.18fr] lg:items-center lg:px-10 lg:py-20"><div className="max-w-2xl"><div className="inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.14em] text-emerald-800">Built for Pakistani businesses</div><h1 className="mt-6 text-[46px] font-semibold leading-[.98] tracking-[-0.055em] sm:text-6xl lg:text-[68px]">Run your business without running after your business.</h1><p className="mt-6 max-w-xl text-[17px] leading-8 text-slate-600">Sales, purchasing, stock, khata, accounting and industry workflows in one operating system built for how Pakistani businesses actually work.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/sign-up" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-6 py-3.5 text-sm font-bold text-white">Sign up <ArrowRight className="size-4"/></Link><Link href="/sign-in" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-800">Login</Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600">{["PKR 29,000 implementation","PKR 5,000/month","Separate business workspace"].map(x=><span key={x} className="flex items-center gap-2"><Check className="size-4 text-emerald-600"/>{x}</span>)}</div></div><ProductFlowPreview/></div></section>

<section className="mx-auto -mt-1 max-w-[1320px] px-5 py-12 sm:px-6 lg:px-10"><div className="grid overflow-hidden rounded-3xl border border-slate-200 bg-white sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Separate business data","Workspace-scoped records and role-aware access."],[Warehouse,"Warehouse control","Stock, receiving, transfers and adjustments."],[Factory,"Industry depth","Wholesale, Restaurant and Manufacturing workflows."],[ReceiptText,"Pakistan-ready","Khata, credit sales, supplier balances and local operations."]].map(([Icon,title,text],i)=>{const I=Icon as typeof ShieldCheck;return <div key={title as string} className={`p-6 ${i?"border-t border-slate-100 sm:border-l sm:border-t-0":""}`}><I className="size-5 text-emerald-700"/><p className="mt-3 text-sm font-bold">{title as string}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text as string}</p></div>})}</div></section>

<section className="bg-[#071821] py-16 text-white sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-8 px-5 sm:px-6 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-400">Real wholesale workflow</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">“Sab kuch aik hi jagah.”</h2><p className="mt-5 max-w-lg text-sm leading-7 text-slate-400">Ahmad Traders is the flagship wholesale proof point: Sales, Purchases, Inventory, Receivables, Cash & Bank, Smart Collections and Reports should not require separate registers.</p><Link href="/industries/wholesale" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-emerald-300">See the customer workflow <ArrowRight className="size-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-[24px] border border-white/10 bg-white/5 p-6"><p className="text-sm font-bold text-rose-300">Before MunshiOS</p><div className="mt-4 space-y-3 text-sm text-slate-400">{["Sales scattered","Stock hard to reconcile","Receivables chased manually","Payments hard to trace"].map(x=><p key={x}>• {x}</p>)}</div></article><article className="rounded-[24px] border border-emerald-400/20 bg-emerald-400/10 p-6"><p className="text-sm font-bold text-emerald-300">Connected workspace</p><div className="mt-4 space-y-3 text-sm text-slate-300">{["Dashboard visibility","Sales + Inventory","Receivables + Cash & Bank","Smart Collections + Reports"].map(x=><p key={x}>• {x}</p>)}</div></article></div></div></section>

<section id="solutions" className="py-16 sm:py-24"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><SectionTitle eyebrow="Solutions" title="Different businesses. Different workflows. One operating system." body="Each industry page is built around the actual operating flow, not a generic ERP feature list."/><div className="mt-12 grid gap-5 lg:grid-cols-2">{[
["Wholesale","/industries/wholesale","Purchasing, GRN, credit sales, receivables, supplier balances and collections.","Flagship customer workflow","wholesale"],
["Restaurant","/industries/restaurant","POS, kitchen, menu, tables, ingredient stock and cash closing.","Restaurant-first workspace","restaurant"],
["Manufacturing","/industries/manufacturing","BOMs, raw materials, production runs, finished goods and wastage.","Production control","manufacturing"],
["Retail","/industries/retail","Sales, stock, khata, suppliers, expenses and daily control.","Daily retail operations","retail"]].map(([title,href,text,accent,type])=><Link href={href} key={title} className="group rounded-[28px] border border-slate-200 bg-white p-5 transition hover:-translate-y-1 hover:border-emerald-300 hover:shadow-[0_28px_70px_-45px_rgba(15,23,42,.35)]"><MiniVisual type={type as "wholesale"|"restaurant"|"manufacturing"|"retail"}/><div className="mt-5 flex items-start justify-between gap-4"><div><h3 className="text-2xl font-bold">{title}</h3><p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">{text}</p></div><span className="hidden text-[9px] font-bold uppercase tracking-[0.12em] text-slate-400 sm:block">{accent}</span></div><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Explore {title} <ArrowRight className="size-4"/></span></Link>)}</div></div></section>

<section className="border-y border-slate-200 bg-white py-16 sm:py-24"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><SectionTitle eyebrow="Connected product" title="One transaction. Everything that depends on it stays in sync." body="The product is designed around business flows, not disconnected module screens."/><div className="mt-12 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[28px] bg-[#071821] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-400">Example workflow</p><h3 className="mt-5 text-3xl font-semibold">Purchase order to payable, without duplicate entry.</h3><p className="mt-5 text-sm leading-7 text-slate-400">Approve a purchase. Receive it. Stock changes. Supplier balance changes. Reports reflect it.</p><div className="mt-7 space-y-3">{["Purchase order approved","Goods received","Warehouse stock updated","Supplier payable updated"].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-full bg-emerald-500 text-xs font-bold text-white">{i+1}</span><span className="text-sm">{x}</span></div>)}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Warehouse,"Inventory","Movements, receiving and stock."],[ShoppingCart,"Sales & khata","Credit sales, receipts and balances."],[PackageCheck,"Purchases & GRN","PO to receiving and supplier ledger."],[CircleDollarSign,"Accounting","Cash, bank, expenses and payables."],[Factory,"Industry workflows","Restaurant and manufacturing depth."],[BarChart3,"Reports","Operational and financial visibility."]].map(([Icon,title,text])=>{const I=Icon as typeof Warehouse;return <article key={title as string} className="rounded-[22px] border border-slate-200 bg-[#fbfcfa] p-5"><div className="mb-5 h-24 rounded-2xl border border-slate-200 bg-white p-3"><div className="flex h-full items-end gap-2">{[42,68,52,82].map((h,i)=><div key={i} className="flex-1 rounded-t bg-emerald-500/70" style={{height:h}}/>)}</div></div><I className="size-5 text-emerald-700"/><h3 className="mt-3 font-bold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text as string}</p></article>})}</div></div><Link href="/product" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Explore the product <ArrowRight className="size-4"/></Link></div></section>

<section className="py-16 sm:py-24"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:items-center lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Restaurant workspace</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-5xl">Service floor, kitchen and cash in one workspace.</h2><p className="mt-5 text-sm leading-7 text-slate-600">Live orders, kitchen status, table occupancy, menu availability, ingredient stock and cash closing.</p><Link href="/industries/restaurant" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Explore Restaurant <ArrowRight className="size-4"/></Link></div><MiniVisual type="restaurant"/></div></section>

<section className="border-y border-slate-200 bg-white py-16 sm:py-24"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><SectionTitle eyebrow="Pricing" title="PKR 29,000 implementation. PKR 5,000 per month." body="One clear commercial model instead of a confusing three-plan wall."/><div className="mt-10 grid gap-5 lg:grid-cols-2"><article className="rounded-[28px] border border-slate-200 bg-[#fbfcfa] p-7"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">One-time implementation</p><p className="mt-4 text-5xl font-semibold tracking-[-0.05em]">PKR 29,000</p><p className="mt-4 text-sm leading-7 text-slate-600">Workspace setup, business configuration, guided onboarding and initial implementation support.</p></article><article className="rounded-[28px] bg-[#071821] p-7 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-emerald-400">Monthly subscription</p><p className="mt-4 text-5xl font-semibold tracking-[-0.05em]">PKR 5,000</p><p className="mt-4 text-sm leading-7 text-slate-400">Ongoing access to MunshiOS, updates and your configured business workspace.</p></article></div><Link href="/pricing" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">See pricing details <ArrowRight className="size-4"/></Link></div></section>

<section className="py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-5 px-5 sm:px-6 lg:grid-cols-2 lg:px-10"><article className="rounded-[26px] border border-slate-200 bg-white p-7"><ShieldCheck className="size-6 text-emerald-700"/><h2 className="mt-5 text-3xl font-semibold">Separate workspace for every business.</h2><p className="mt-4 text-sm leading-7 text-slate-600">Your records stay scoped to your business workspace, with role-aware access for the people you add.</p><Link href="/security" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Security architecture <ArrowRight className="size-4"/></Link></article><article className="rounded-[26px] bg-emerald-50 p-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-emerald-700">Commercial model</p><h2 className="mt-5 text-3xl font-semibold">Implementation first. Subscription after.</h2><p className="mt-4 text-sm leading-7 text-slate-600">PKR 29,000 one-time implementation + PKR 5,000/month.</p><Link href="/pricing" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">See pricing <ArrowRight className="size-4"/></Link></article></div></section>
<CTA/><MarketingFooter/></main>}