import { BarChart3, Boxes, Check, CircleDollarSign, Factory, PackageCheck, ReceiptText, ShoppingCart, UtensilsCrossed, Warehouse } from "lucide-react";

export function WholesaleVisual({dark=false}:{dark?:boolean}) {
  return <div data-marketing-lift className={`overflow-hidden rounded-[22px] sm:rounded-[28px] border ${dark?"border-white/10 bg-[#061D2E] text-white":"border-slate-200 bg-white text-slate-950"}`}>
    <div className={`flex items-center justify-between border-b px-3 py-2.5 sm:px-4 sm:py-3 ${dark?"border-white/10":"border-slate-100"}`}><div><p className={`text-[10px] font-bold uppercase tracking-[.16em] ${dark?"text-emerald-300":"text-emerald-700"}`}>Wholesale control</p><p className={`mt-1 text-xs ${dark?"text-slate-400":"text-slate-500"}`}>Receivables, stock and collections in one operating view</p><p className={`mt-1 text-[8px] uppercase tracking-[.12em] ${dark?"text-slate-600":"text-slate-400"}`}>Illustrative workspace · sample data</p></div><Warehouse className={`size-5 ${dark?"text-emerald-300":"text-emerald-700"}`}/></div>
    <div className="grid gap-2.5 p-3 sm:gap-3 sm:p-4 sm:grid-cols-[1.1fr_.9fr]">
      <div className={`rounded-2xl border p-4 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-[#f8faf9]"}`}><div className="grid grid-cols-3 gap-2">{[["Receivables","842k"],["Stock","2.1m"],["Due","14"]].map(([a,b],i)=><div key={a} className={`rounded-xl p-3 ${dark?"bg-black/10":"bg-white"}`}><p className={`text-[9px] ${dark?"text-slate-500":"text-slate-400"}`}>{a}</p><p className="mt-1 text-sm font-bold">{b}</p><div className={`mt-2 h-1.5 rounded-full ${dark?"bg-white/10":"bg-slate-100"}`}><div className={`h-full rounded-full ${i===2?"w-[46%] bg-amber-400":"w-[72%] bg-emerald-500"}`}/></div></div>)}</div>
      <div className="mt-3 overflow-hidden rounded-xl">{[["INV-1042","Credit sale","126,400"],["RCPT-518","Collection","84,000"],["GRN-0821","Receiving","286,400"]].map(([a,b,c])=><div key={a} className={`grid grid-cols-[.8fr_1fr_.7fr] gap-2 border-b px-3 py-2.5 text-[9px] last:border-0 ${dark?"border-white/10 bg-black/10 text-slate-300":"border-slate-100 bg-white text-slate-600"}`}><b className={dark?"text-emerald-300":"text-emerald-700"}>{a}</b><span>{b}</span><span className="text-right">{c}</span></div>)}</div></div>
      <div className={`rounded-2xl border p-4 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`}><p className={`text-[9px] font-bold uppercase tracking-[.14em] ${dark?"text-slate-500":"text-slate-400"}`}>Collection priority</p><div className="mt-4 space-y-3">{[["Customer A","186k","7d"],["Customer B","142k","3d"],["Customer C","96k","today"]].map(([a,b,c],i)=><div key={a}><div className="flex items-center justify-between text-[10px]"><span>{a}</span><b>{b}</b></div><div className={`mt-1.5 h-1.5 rounded-full ${dark?"bg-white/10":"bg-slate-100"}`}><div className={`h-full rounded-full ${i===0?"w-[86%] bg-amber-400":i===1?"w-[68%] bg-emerald-400":"w-[48%] bg-slate-400"}`}/></div><p className={`mt-1 text-[8px] ${dark?"text-slate-500":"text-slate-400"}`}>{c}</p></div>)}</div></div>
    </div>
  </div>;
}

export function RestaurantVisual({dark=true}:{dark?:boolean}) {
  return <div data-marketing-lift className={`overflow-hidden rounded-[22px] sm:rounded-[28px] border ${dark?"border-white/10 bg-[#061D2E] text-white":"border-slate-200 bg-white"}`}>
    <div className={`flex items-center justify-between border-b px-3 py-2.5 sm:px-4 sm:py-3 ${dark?"border-white/10":"border-slate-100"}`}><div><p className={`text-[10px] font-bold uppercase tracking-[.16em] ${dark?"text-emerald-300":"text-emerald-700"}`}>Kitchen display</p><p className={`mt-1 text-xs ${dark?"text-slate-500":"text-slate-500"}`}>Orders move through service, not between apps</p></div><UtensilsCrossed className={dark?"size-5 text-emerald-300":"size-5 text-emerald-700"}/></div>
    <div className="grid gap-2.5 p-3 sm:gap-3 sm:p-4 sm:grid-cols-3">{[["NEW","5",["#R-136 · T03","#R-137 · Takeaway"]],["PREPARING","7",["#R-132 · T08","#R-133 · Delivery"]],["READY","4",["#R-128 · T04","#R-129 · T11"]]].map(([title,count,items],i)=><div key={title as string} className={`rounded-xl border p-2 sm:rounded-2xl sm:p-3 ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-[#f8faf9]"}`}><div className="flex items-center justify-between"><span className={`text-[9px] font-bold ${i===2?"text-emerald-300":i===1?"text-amber-300":"text-slate-400"}`}>{title as string}</span><span className="text-sm font-bold sm:text-lg">{count as string}</span></div><div className="mt-2 space-y-1.5 sm:mt-3 sm:space-y-2">{(items as string[]).map((x,j)=><div key={x} className={`rounded-lg border p-1.5 sm:rounded-xl sm:p-2.5 ${dark?"border-white/10 bg-black/10":"border-slate-200 bg-white"}`}><p className="text-[9px] font-semibold">{x}</p><div className={`mt-2 h-1.5 rounded-full ${dark?"bg-white/10":"bg-slate-100"}`}><div className={`h-full rounded-full ${i===2?"w-full bg-emerald-400":i===1?"w-[70%] bg-amber-400":"w-[35%] bg-slate-400"}`}/></div></div>)}</div></div>)}</div>
  </div>;
}

export function ManufacturingVisual() {
  return <div data-marketing-lift className="overflow-hidden rounded-[22px] sm:rounded-[28px] border border-slate-200 bg-white">
    <div className="flex items-center justify-between border-b border-slate-100 px-3 py-2.5 sm:px-4 sm:py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-700">Production run</p><p className="mt-1 text-xs text-slate-500">Material in → finished goods out</p></div><Factory className="size-5 text-emerald-700"/></div>
    <div className="grid gap-2.5 p-3 sm:gap-3 sm:p-4 sm:grid-cols-[.85fr_1.15fr]"><div className="rounded-2xl bg-[#061D2E] p-4 text-white"><p className="text-[9px] uppercase tracking-[.14em] text-slate-500">RUN-0248</p><h3 className="mt-2 text-lg font-semibold">Rear Hub Assembly</h3><div className="mt-5 space-y-3">{[["Raw material","320 kg","bg-slate-400"],["Consumed","298 kg","bg-emerald-400"],["Wastage","6.1 kg","bg-amber-400"]].map(([a,b,c])=><div key={a}><div className="flex justify-between text-[10px]"><span className="text-slate-400">{a}</span><b>{b}</b></div><div className="mt-1.5 h-1.5 rounded bg-white/10"><div className={`h-full rounded ${c} ${a==="Wastage"?"w-[18%]":"w-[82%]"}`}/></div></div>)}</div><div className="mt-5 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3"><p className="text-[9px] text-emerald-300">Finished output</p><p className="mt-1 text-2xl font-semibold">118 pcs</p></div></div>
      <div className="rounded-2xl border border-slate-200 bg-[#f8faf9] p-4"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-slate-400">Flow</p><div className="mt-4 space-y-3">{[[ShoppingCart,"Purchase","Raw material received"],[PackageCheck,"Issue","Material issued to run"],[Factory,"Produce","Output recorded"],[Warehouse,"Finished goods","Warehouse updated"]].map(([Icon,a,b],i)=>{const I=Icon as typeof Factory;return <div key={a as string} className="flex items-center gap-3"><div className={`grid size-9 place-items-center rounded-xl ${i===3?"bg-emerald-600 text-white":"border border-slate-200 bg-white text-slate-600"}`}><I className="size-4"/></div><div><p className="text-[10px] font-bold">{a as string}</p><p className="text-[9px] text-slate-500">{b as string}</p></div></div>})}</div></div></div>
  </div>;
}

export function RetailVisual() {
  return <div data-marketing-lift className="overflow-hidden rounded-[22px] sm:rounded-[28px] border border-slate-200 bg-white">
    <div className="flex items-center justify-between border-b border-slate-100 px-3 py-2.5 sm:px-4 sm:py-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-700">Retail daily control</p><p className="mt-1 text-xs text-slate-500">Sales, stock and khata at a glance</p></div><ReceiptText className="size-5 text-emerald-700"/></div>
    <div className="grid gap-2.5 p-3 sm:gap-3 sm:p-4 sm:grid-cols-[1fr_.9fr]"><div><div className="grid grid-cols-3 gap-2">{[["Sales","126k"],["Low stock","9"],["Khata","214k"]].map(([a,b],i)=><div key={a} className="rounded-xl border border-slate-200 bg-[#f8faf9] p-3"><p className="text-[9px] text-slate-400">{a}</p><p className="mt-1 text-sm font-bold">{b}</p><div className={`mt-2 h-1.5 rounded ${i===1?"bg-amber-300":"bg-emerald-300"}`}/></div>)}</div><div className="mt-3 overflow-hidden rounded-xl border border-slate-200">{[["INV-1481","Cash","8,450"],["INV-1480","Credit","12,900"],["INV-1479","Cash","4,250"]].map(([a,b,c])=><div key={a} className="grid grid-cols-[.8fr_.7fr_.7fr] gap-2 border-b border-slate-100 bg-white px-3 py-2.5 text-[9px] last:border-0"><b className="text-emerald-700">{a}</b><span>{b}</span><span className="text-right">{c}</span></div>)}</div></div>
      <div className="rounded-2xl bg-[#061D2E] p-4 text-white"><p className="text-[9px] uppercase tracking-[.14em] text-slate-500">Stock pressure</p><div className="mt-4 space-y-4">{[["Engine oil","3 left",82],["Brake shoe","5 left",66],["Bearing 6204","9 left",48]].map(([a,b,v])=><div key={a as string}><div className="flex justify-between text-[10px]"><span>{a as string}</span><span className="text-amber-300">{b as string}</span></div><div className="mt-1.5 h-1.5 rounded bg-white/10"><div className="h-full rounded bg-amber-400" style={{width:`${v}%`}}/></div></div>)}</div></div></div>
  </div>;
}

export function ConnectedOperationsCanvas() {
  const steps=[[ShoppingCart,"Purchase","PO approved"],[PackageCheck,"Receive","GRN posted"],[Warehouse,"Stock","Inventory updated"],[ReceiptText,"Sell","Credit sale"],[CircleDollarSign,"Collect","Payment allocated"],[BarChart3,"Report","Same source data"]] as const;
  return <div data-marketing-lift className="overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-[0_30px_80px_-48px_rgba(15,23,42,.38)] sm:rounded-[30px]"><div className="border-b border-slate-100 px-4 py-3.5 sm:px-5 sm:py-4"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#087C72]">Connected operations</p><p className="mt-1 text-sm font-semibold text-slate-900">One action changes the records that depend on it.</p></div><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-3 sm:gap-3 sm:p-5 lg:grid-cols-6">{steps.map(([Icon,title,sub],i)=>{const I=Icon as typeof Warehouse;return <div key={title} className={`relative rounded-xl border p-3 sm:rounded-2xl sm:p-4 ${i===5?"border-[#11B79E]/30 bg-[#11B79E]/8":"border-slate-200 bg-[#f8faf9]"}`}><div className={`grid size-9 place-items-center rounded-xl ${i===5?"bg-[#0A8F82] text-white":"bg-white text-slate-600 ring-1 ring-slate-200"}`}><I className="size-4"/></div><p className="mt-3 text-xs font-bold sm:mt-4">{title}</p><p className="mt-1 text-[9px] leading-4 text-slate-500">{sub}</p>{i<steps.length-1&&<span className="absolute -right-[7px] top-1/2 hidden h-px w-3 bg-[#11B79E]/35 lg:block"/>}</div>})}</div></div>;
}
