import { PageHeader } from "@/components/business/page-header";
import { PurchaseForm } from "@/components/purchases/purchase-form";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { requireWorkspace } from "@/lib/server/auth";
import { db } from "@/lib/server/db";
import { listPurchases } from "@/lib/server/purchases";
import { formatDate, formatPKR } from "@/lib/utils";
export default async function PurchasesPage() { const { workspaceId, role } = await requireWorkspace(); const [purchases, suppliers, products] = await Promise.all([listPurchases(workspaceId), db.supplier.findMany({ where: { workspaceId }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.product.findMany({ where: { workspaceId, status: "ACTIVE" }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); return <div className="space-y-6"><PageHeader title="Purchases" description="Receive stock and track supplier payables atomically." />{role !== "STAFF" && <PurchaseForm suppliers={suppliers} products={products} />}<Card className="gap-0 py-0 shadow-none"><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Supplier</TableHead><TableHead>Date</TableHead><TableHead className="text-right">Total</TableHead><TableHead className="text-right">Balance</TableHead></TableRow></TableHeader><TableBody>{purchases.map((row) => <TableRow key={row.id}><TableCell className="font-mono text-xs">{row.orderNumber}</TableCell><TableCell>{row.supplierName}</TableCell><TableCell>{formatDate(row.date)}</TableCell><TableCell className="text-right">{formatPKR(row.total)}</TableCell><TableCell className="text-right font-semibold">{formatPKR(row.balance)}</TableCell></TableRow>)}{!purchases.length && <TableRow><TableCell colSpan={5} className="h-32 text-center text-neutral-500">No purchases yet.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></div>; }
