"use client";

import { useDeferredValue, useState } from "react";
import { CircleDollarSign, FileText, Search, TriangleAlert } from "lucide-react";
import { MetricCard } from "@/components/business/metric-card";
import { PageHeader } from "@/components/business/page-header";
import { StatusBadge } from "@/components/business/status-badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DEMO_INVOICES } from "@/lib/demo-data";
import { formatDate, formatPKR } from "@/lib/utils";

export default function InvoicesPage() {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const deferredQuery = useDeferredValue(query.toLowerCase().trim());
  const invoices = DEMO_INVOICES.filter((invoice) => `${invoice.invoiceNumber} ${invoice.customerName} ${invoice.orderId}`.toLowerCase().includes(deferredQuery) && (status === "ALL" || invoice.status === status));
  const billed = DEMO_INVOICES.reduce((sum, invoice) => sum + invoice.total, 0); const outstanding = DEMO_INVOICES.reduce((sum, invoice) => sum + invoice.balance, 0);
  return <main className="space-y-6 p-4 md:p-6 lg:p-8"><PageHeader title="Invoices" description="Review customer billing, collections, and due dates." />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label="Total billed" value={formatPKR(billed)} detail={`${DEMO_INVOICES.length} issued invoices`} icon={FileText} /><MetricCard label="Outstanding" value={formatPKR(outstanding)} detail={`${Math.round((outstanding / billed) * 100)}% of billed amount`} icon={CircleDollarSign} /><MetricCard label="Overdue" value={`${DEMO_INVOICES.filter((invoice) => invoice.status === "OVERDUE").length} invoice`} detail="Requires collection follow-up" icon={TriangleAlert} /></section>
    <Card className="gap-0 py-0 shadow-none"><CardHeader className="gap-3 border-b py-4 lg:flex lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">Invoice register</h2><p className="text-sm text-neutral-500">{invoices.length} invoices shown</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative sm:w-72"><Search className="pointer-events-none absolute left-2.5 top-2 h-4 w-4 text-neutral-400" /><Input className="pl-8" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Invoice, customer, order..." /><span className="sr-only">Search invoices</span></label><select aria-label="Filter invoice status" value={status} onChange={(event) => setStatus(event.target.value)} className="h-8 rounded-lg border border-input bg-background px-2.5 text-sm outline-none focus:border-ring focus:ring-3 focus:ring-ring/50"><option value="ALL">All statuses</option><option value="PAID">Paid</option><option value="PARTIALLY_PAID">Partially paid</option><option value="UNPAID">Unpaid</option><option value="OVERDUE">Overdue</option></select></div></CardHeader>
      <CardContent className="p-0"><Table><TableHeader className="bg-neutral-50/80"><TableRow><TableHead className="pl-4">Invoice</TableHead><TableHead>Customer</TableHead><TableHead className="hidden md:table-cell">Issued</TableHead><TableHead className="hidden lg:table-cell">Due</TableHead><TableHead className="hidden text-right sm:table-cell">Total</TableHead><TableHead className="text-right">Balance</TableHead><TableHead className="hidden pr-4 xl:table-cell">Status</TableHead></TableRow></TableHeader><TableBody>{invoices.map((invoice) => <TableRow key={invoice.id}><TableCell className="pl-4"><p className="font-mono text-xs font-semibold">{invoice.invoiceNumber}</p><p className="mt-1 text-xs text-neutral-500">{invoice.orderId.toUpperCase()}</p></TableCell><TableCell className="font-medium">{invoice.customerName}<div className="mt-1 xl:hidden"><StatusBadge status={invoice.status} /></div></TableCell><TableCell className="hidden text-neutral-600 md:table-cell">{formatDate(invoice.date)}</TableCell><TableCell className="hidden text-neutral-600 lg:table-cell">{formatDate(invoice.dueDate)}</TableCell><TableCell className="hidden text-right tabular-nums sm:table-cell">{formatPKR(invoice.total)}</TableCell><TableCell className="text-right font-semibold tabular-nums">{formatPKR(invoice.balance)}</TableCell><TableCell className="hidden pr-4 xl:table-cell"><StatusBadge status={invoice.status} /></TableCell></TableRow>)}{invoices.length === 0 && <TableRow><TableCell colSpan={7} className="h-32 text-center text-neutral-500">No invoices match these filters.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></main>;
}
