import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, CircleDollarSign, ReceiptText, Store, UtensilsCrossed, Warehouse } from "lucide-react";
import { MarketingHeader, MarketingFooter, CTA } from "@/components/marketing/site";
import { RestaurantVisual } from "@/components/marketing/premium-visuals";

export const metadata: Metadata = { title:"Restaurant Operations Software Pakistan", description:"Restaurant software for Pakistani businesses with POS, tables, kitchen display, menu, ingredient stock and cash closing.", alternates:{canonical:"/industries/restaurant"}, openGraph:{title:"Restaurant Operations Software Pakistan | MunshiOS",description:"Restaurant software for Pakistani businesses with POS, tables, kitchen display, menu, ingredient stock and cash closing.",url:"/industries/restaurant",type:"website"}, twitter:{card:"summary_large_image",title:"Restaurant Operations Software Pakistan | MunshiOS",description:"Restaurant software for Pakistani businesses with POS, tables, kitchen display, menu, ingredient stock and cash closing."} };

export default function RestaurantPage(){return <main className="min-h-screen bg-[#fbfcfa] text-slate-950"><MarketingHeader/>
<section className="bg-white"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[.76fr_1.24fr] lg:items-center lg:px-10 lg:py-20"><div className="max-w-xl"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-emerald-800"><span className="h-px w-6 bg-emerald-500"/>Restaurant operations</div><h1 className="mt-6 text-5xl font-semibold leading-[.98] tracking-[-.058em] sm:text-6xl">From first order to final cash count.</h1><p className="mt-6 text-base leading-8 text-slate-600 sm:text-lg">POS, kitchen display, tables, menu availability, ingredient stock and shift closing in one service flow.</p><div className="mt-8 flex gap-3"><Link href="/sign-up" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#061D2E] px-5 py-3 text-sm font-bold text-white">Get MunshiOS <ArrowRight className="size-4"/></Link><Link href="/pricing" className="inline-flex min-h-12 items-center rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">Pricing</Link></div></div><RestaurantVisual/></div></section>
<section className="bg-[#061D2E] py-16 text-white sm:py-20"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.68fr_1.32fr]"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300">During service</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">The order should move. The staff should not chase it.</h2><p className="mt-5 text-sm leading-7 text-slate-400">A dine-in or takeaway order should move through service with one state, one kitchen queue and one final financial outcome.</p></div><div className="grid gap-x-6 gap-y-0 sm:grid-cols-2">{[["01","Take order","POS / table"],["02","Kitchen queue","Send instantly"],["03","Prepare","Live KDS state"],["04","Serve","Order completed"],["05","Payment","Cash / bank"],["06","Close shift","Count and variance"]].map(([n,a,b],i)=><div key={a} className="border-t border-white/10 py-5"><div className="flex gap-4"><span className={`text-[10px] font-bold ${i===5?"text-emerald-300":"text-slate-500"}`}>{n}</span><div><p className="text-sm font-bold">{a}</p><p className="mt-1 text-xs text-slate-500">{b}</p></div></div></div>)}</div></div></div></section>
<section className="py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:px-10"><RestaurantVisual dark={false}/><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">Restaurant-first workspace</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Built around the questions that matter during a shift.</h2><div className="mt-7 divide-y divide-slate-200 border-y border-slate-200">{[[UtensilsCrossed,"What needs attention now?","Live order and table state"],[Store,"What can we sell?","Menu availability"],[Warehouse,"What are we running out of?","Ingredient inventory"],[CircleDollarSign,"What did the shift close at?","Cash and variance"],[BarChart3,"What happened today?","Restaurant and financial reporting"]].map(([Icon,q,a])=>{const I=Icon as typeof Store;return <div key={q as string} className="flex items-center gap-4 py-4"><I className="size-4 text-emerald-700"/><div><p className="text-sm font-bold">{q as string}</p><p className="mt-1 text-xs text-slate-500">{a as string}</p></div></div>})}</div></div></div></section>
<CTA title="Keep service moving from order to close."/><MarketingFooter/></main>}