import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, CircleDollarSign, LayoutDashboard, ReceiptText, ShieldCheck, ShoppingCart, Warehouse } from "lucide-react";
import { MarketingHeader, MarketingFooter, CTA } from "@/components/marketing/site";
import { ConnectedOperationsCanvas, ManufacturingVisual, RestaurantVisual, RetailVisual, WholesaleVisual } from "@/components/marketing/premium-visuals";

export const metadata: Metadata = {
  title: "Product | MunshiOS",
  description: "See how MunshiOS connects purchasing, GRN, inventory, sales, khata, accounting and reporting in one system.",
  alternates: { canonical: "/product" },
};

function ProductLedgerVisual() {
  return <div className="overflow-hidden rounded-[30px] border border-slate-200 bg-white shadow-[0_30px_80px_-50px_rgba(15,23,42,.4)]">
    <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-700">Live business context</p><p className="mt-1 text-sm font-semibold">Customer sale → receivable → payment</p></div><CircleDollarSign className="size-5 text-emerald-700"/></div>
    <div className="grid gap-3 p-4 sm:grid-cols-[1.05fr_.95fr]"><div className="rounded-2xl border border-slate-200 bg-[#f8faf9] p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] text-slate-400">Invoice</p><p className="mt-1 text-sm font-bold">INV-1042</p></div><div className="text-right"><p className="text-[9px] text-slate-400">Total</p><p className="mt-1 text-sm font-bold">Rs 126,400</p></div></div><div className="mt-4 space-y-2">{[["Rear hub","40 pcs","72,000"],["Bearing set","40 sets","38,400"],["Oil seal","40 pcs","16,000"]].map(([a,b,c])=><div key={a} className="grid grid-cols-[1fr_.6fr_.6fr] gap-2 rounded-xl bg-white px-3 py-2 text-[9px]"><span className="font-semibold">{a}</span><span className="text-slate-500">{b}</span><span className="text-right">{c}</span></div>)}</div><div className="mt-4 flex items-center justify-between border-t border-slate-200 pt-3 text-[10px]"><span className="text-slate-500">Customer balance</span><b className="text-emerald-700">Updated automatically</b></div></div><div className="rounded-2xl bg-[#071821] p-4 text-white"><p className="text-[9px] uppercase tracking-[.14em] text-slate-500">Collection trail</p><div className="mt-4 space-y-4">{[["Credit sale","126,400","posted"],["Payment received","84,000","allocated"],["Balance","42,400","open"]].map(([a,b,c],i)=><div key={a} className="relative pl-5"><span className={`absolute left-0 top-1.5 size-2 rounded-full ${i===2?"bg-amber-400":"bg-emerald-400"}`}/>{i<2&&<span className="absolute left-[3px] top-4 h-7 w-px bg-white/15"/>}<p className="text-[10px] font-semibold">{a}</p><div className="mt-1 flex justify-between text-[9px] text-slate-400"><span>Rs {b}</span><span>{c}</span></div></div>)}</div></div></div>
  </div>;
}

export default function ProductPage(){
  return <main className="min-h-screen bg-[#fbfcfa] text-slate-950">
    <MarketingHeader/>

    <section className="bg-white"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[.78fr_1.22fr] lg:items-center lg:px-10 lg:py-20"><div className="max-w-xl"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-emerald-800"><span className="h-px w-6 bg-emerald-500"/>Product</div><h1 className="mt-6 text-5xl font-semibold leading-[.98] tracking-[-.058em] sm:text-6xl">One system. Connected consequences.</h1><p className="mt-6 text-base leading-8 text-slate-600 sm:text-lg">MunshiOS is designed around business events, not disconnected screens. What happens in one workflow carries into the records that depend on it.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/sign-up" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#071821] px-5 py-3 text-sm font-bold text-white">Get MunshiOS <ArrowRight className="size-4"/></Link><Link href="/pricing" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold">See pricing</Link></div></div><ProductLedgerVisual/></div></section>

    <section className="border-y border-slate-200 bg-white py-16 sm:py-20"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.68fr_1.32fr] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">Operational spine</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Enter the event once. Let the business context travel.</h2><p className="mt-5 text-sm leading-7 text-slate-600">The value is not another dashboard. It is the chain between purchasing, receiving, inventory, sales, receivables, payments and reporting.</p></div><ConnectedOperationsCanvas/></div></div></section>

    <section className="py-16 sm:py-20"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><div className="max-w-3xl"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">One platform, different operating surfaces</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">The workspace should look like the work.</h2><p className="mt-5 text-sm leading-7 text-slate-600">Wholesale, restaurant, retail and manufacturing use the same foundation without being forced into the same screen design.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-12"><div className="lg:col-span-7"><WholesaleVisual/></div><div className="lg:col-span-5"><RestaurantVisual/></div><div className="lg:col-span-5"><RetailVisual/></div><div className="lg:col-span-7"><ManufacturingVisual/></div></div></div></section>

    <section className="border-y border-slate-200 bg-[#071821] py-16 text-white sm:py-20"><div className="mx-auto max-w-[1320px] px-5 sm:px-6 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.76fr_1.24fr]"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300">Under the interface</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">ERP depth without making the operator think like an ERP.</h2><p className="mt-5 text-sm leading-7 text-slate-400">The daily screens stay focused while accounting, inventory and workspace context remain underneath the transaction.</p></div><div className="grid gap-x-8 gap-y-6 sm:grid-cols-2">{[[ShoppingCart,"Sales & purchasing","Cash, credit, returns, receipts and purchasing."],[Warehouse,"Inventory","Receiving, warehouse movements and adjustments."],[CircleDollarSign,"Finance","Cash, bank, expenses, customer and supplier balances."],[Boxes,"Industry logic","Restaurant and manufacturing workflows on the same platform."],[ShieldCheck,"Workspace control","Business isolation, membership and role-aware access."],[BarChart3,"Reporting","Operational and financial visibility from shared records."]].map(([Icon,a,b],i)=>{const I=Icon as typeof Warehouse;return <div key={a as string} className="border-t border-white/10 pt-4"><div className="flex items-center gap-3"><I className={`size-4 ${i===2?"text-amber-300":"text-emerald-300"}`}/><h3 className="text-sm font-bold">{a as string}</h3></div><p className="mt-2 text-xs leading-5 text-slate-400">{b as string}</p></div>})}</div></div></div></section>

    <section className="py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-6 px-5 sm:px-6 lg:grid-cols-[1.08fr_.92fr] lg:px-10"><div className="border-y border-slate-200 py-8"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Workspace model</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Every business gets its own operating context.</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-slate-600">Products, customers, suppliers, sales, purchases, inventory, expenses, accounts and reports remain scoped to the selected workspace.</p></div><div className="rounded-[28px] border border-slate-200 bg-white p-6"><LayoutDashboard className="size-5 text-emerald-700"/><h3 className="mt-5 text-2xl font-semibold">Different people. Different access.</h3><div className="mt-5 space-y-3">{[["Owner","Full business visibility"],["Manager","Operational control"],["Staff","Task-focused access"]].map(([a,b])=><div key={a} className="flex items-center justify-between border-b border-slate-100 pb-3 text-sm last:border-0"><b>{a}</b><span className="text-slate-500">{b}</span></div>)}</div><Link href="/security" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-emerald-700">Security architecture <ArrowRight className="size-4"/></Link></div></div></section>

    <CTA title="One place for the operation to stay connected."/>
    <MarketingFooter/>
  </main>;
}