import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, CircleDollarSign, ReceiptText, ShoppingCart, Store, Warehouse } from "lucide-react";
import { MarketingHeader, MarketingFooter, CTA } from "@/components/marketing/site";
import { RetailVisual } from "@/components/marketing/premium-visuals";

export const metadata: Metadata = { title:"Retail Accounting & Inventory Software Pakistan", description:"Retail software for Pakistani shops with sales, inventory, purchases, customer khata, supplier balances, expenses and daily reporting.", alternates:{canonical:"/industries/retail"}, openGraph:{title:"Retail Accounting & Inventory Software Pakistan | MunshiOS",description:"Retail software for Pakistani shops with sales, inventory, purchases, customer khata, supplier balances, expenses and daily reporting.",url:"/industries/retail",type:"website"}, twitter:{card:"summary_large_image",title:"Retail Accounting & Inventory Software Pakistan | MunshiOS",description:"Retail software for Pakistani shops with sales, inventory, purchases, customer khata, supplier balances, expenses and daily reporting."} };

export default function RetailPage(){return <main className="min-h-screen bg-[#fbfcfa] text-slate-950"><MarketingHeader/>
<section className="bg-white"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[.76fr_1.24fr] lg:items-center lg:px-10 lg:py-20"><div className="max-w-xl"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-emerald-800"><span className="h-px w-6 bg-emerald-500"/>Retail daily control</div><h1 className="mt-6 text-5xl font-semibold leading-[.98] tracking-[-.058em] sm:text-6xl">Know what sold, what is left, and who still owes you.</h1><p className="mt-6 text-base leading-8 text-slate-600 sm:text-lg">Sales, stock, purchases, customer khata, supplier balances, expenses and daily reporting in one retail workspace.</p><div className="mt-8 flex gap-3"><Link href="/get-your-munshi" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#061D2E] px-5 py-3 text-sm font-bold text-white">Get MunshiOS <ArrowRight className="size-4"/></Link><Link href="/pricing" className="inline-flex min-h-12 items-center rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold">Pricing</Link></div></div><RetailVisual/></div></section>
<section className="py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-[.72fr_1.28fr] lg:px-10"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">Daily questions</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">A retailer should not need six registers to answer six simple questions.</h2></div><div className="grid gap-x-6 sm:grid-cols-2">{[[ReceiptText,"What sold today?","Sales"],[Warehouse,"What is running low?","Stock"],[CircleDollarSign,"Who owes us?","Customer khata"],[ShoppingCart,"What do we need to buy?","Suppliers"],[Store,"What did we spend?","Expenses"],[BarChart3,"How did the day finish?","Reports"]].map(([Icon,q,a])=>{const I=Icon as typeof Store;return <div key={q as string} className="border-t border-slate-200 py-5"><div className="flex items-center gap-3"><I className="size-4 text-emerald-700"/><div><p className="text-sm font-bold">{q as string}</p><p className="mt-1 text-xs text-slate-500">{a as string}</p></div></div></div>})}</div></div></section>
<section className="border-y border-slate-200 bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-10"><RetailVisual/><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">One sale, less admin</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">The transaction should do more than print a receipt.</h2><p className="mt-5 text-sm leading-7 text-slate-600">A sale can update stock, customer balance and reporting context while the operator stays focused on the counter.</p><div className="mt-7 flex flex-wrap gap-2">{["Sell","Update stock","Track khata","Receive payment","Review reports"].map((x,i)=><span key={x} className={`rounded-full border px-3 py-2 text-xs font-semibold ${i===4?"border-emerald-200 bg-emerald-50 text-emerald-800":"border-slate-200 bg-white"}`}>{x}</span>)}</div></div></div></section>
<CTA title="Run the day without rebuilding the day."/><MarketingFooter/></main>}