import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleDollarSign, LayoutDashboard, LockKeyhole, ReceiptText, ShieldCheck } from "lucide-react";
import { MarketingHeader, MarketingFooter, CTA } from "@/components/marketing/site";

export const metadata: Metadata = { title:"Security | MunshiOS", description:"How MunshiOS protects workspace access, tenant isolation, authentication and operational integrity.", alternates:{canonical:"/security"} };

function AccessStack(){
  const steps=[["01","Identity","Verified user session"],["02","Membership","User belongs to this workspace"],["03","Role","Permission allows the action"],["04","Tenant scope","Query stays inside the workspace"],["05","Invariant","Server validates the business rule"]] as const;
  return <div className="overflow-hidden rounded-[30px] bg-[#061D2E] p-5 text-white shadow-[0_30px_85px_-50px_rgba(15,23,42,.55)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-emerald-300">Workspace access</p><p className="mt-1 text-sm font-semibold">Five checks before the business action</p></div><ShieldCheck className="size-5 text-emerald-300"/></div><div className="mt-6 space-y-2">{steps.map(([n,a,b],i)=><div key={a} className={`grid grid-cols-[auto_1fr_auto] items-center gap-3 border-b border-white/10 py-3 last:border-0 ${i===4?"text-emerald-200":""}`}><span className="text-[9px] font-bold text-slate-500">{n}</span><div><p className="text-sm font-semibold">{a}</p><p className="mt-1 text-[10px] text-slate-500">{b}</p></div><Check className={`size-4 ${i===4?"text-emerald-300":"text-slate-600"}`}/></div>)}</div></div>;
}

export default function SecurityPage(){return <main className="min-h-screen bg-[#fbfcfa] text-slate-950"><MarketingHeader/>
<section className="bg-white"><div className="mx-auto grid max-w-[1400px] gap-12 px-5 py-14 sm:px-6 lg:grid-cols-[.76fr_1.24fr] lg:items-center lg:px-10 lg:py-20"><div className="max-w-xl"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.16em] text-emerald-800"><span className="h-px w-6 bg-emerald-500"/>Security architecture</div><h1 className="mt-6 text-5xl font-semibold leading-[.98] tracking-[-.058em] sm:text-6xl">Your business data should stay your business data.</h1><p className="mt-6 text-base leading-8 text-slate-600 sm:text-lg">MunshiOS is designed around authenticated users, workspace membership, role-aware access, tenant-scoped operations and server-side business rules.</p><Link href="/sign-up" className="mt-8 inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#061D2E] px-5 py-3 text-sm font-bold text-white">Get MunshiOS <ArrowRight className="size-4"/></Link></div><AccessStack/></div></section>
<section className="border-y border-slate-200 bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-700">Isolation</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">Signing in is only the first gate.</h2><p className="mt-5 text-sm leading-7 text-slate-600">The system still needs to know which workspace the user belongs to, what role they hold and whether the action stays inside the right business context.</p></div><div className="divide-y divide-slate-200 border-y border-slate-200">{[[LockKeyhole,"Authentication","Verified email, password login and protected recovery flows."],[LayoutDashboard,"Workspace membership","A signed-in user still needs membership in the selected workspace."],[ShieldCheck,"Tenant isolation","Workspace-aware reads and writes are designed to prevent cross-business mixing."],[Check,"Roles and permissions","Owners, admins, managers and staff can have different access."],[CircleDollarSign,"Server validation","Sensitive actions do not rely on browser trust."],[ReceiptText,"Operational integrity","Financial and inventory actions preserve business context."]].map(([Icon,a,b])=>{const I=Icon as typeof ShieldCheck;return <div key={a as string} className="flex gap-5 py-5"><I className="mt-0.5 size-4 shrink-0 text-emerald-700"/><div><h3 className="text-sm font-bold">{a as string}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{b as string}</p></div></div>})}</div></div></section>
<section className="bg-[#061D2E] py-16 text-white sm:py-20"><div className="mx-auto grid max-w-[1320px] gap-10 px-5 sm:px-6 lg:grid-cols-2 lg:px-10"><div className="border-t border-white/15 pt-6"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300">Financial actions</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">A button click should not be enough to break the books.</h2><p className="mt-5 text-sm leading-7 text-slate-400">Payments, returns, voids, stock movements and accounting flows are guarded by server-side rules and business invariants rather than UI assumptions.</p></div><div className="border-t border-white/15 pt-6"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-emerald-300">Recovery</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em]">Account recovery should return the user safely.</h2><p className="mt-5 text-sm leading-7 text-slate-400">Password recovery, email verification and post-login routing are designed to return users to the correct workspace without weakening the access model.</p></div></div></section>
<CTA title="Security is part of the operating system, not a badge in the footer."/><MarketingFooter/></main>}